spring:
  application:
    name: nutrition-api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: userprofile
          uri: http://localhost:8081
          predicates:
            - Path=/userProfile/**
        - id: nutrition-service
          uri: http://localhost:8083
          predicates:
            - Path=/nutrition/**
        - id: wishlist
          uri: http://localhost:8084
          predicates:
            - Path=/wishlist/**

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
